name: C/C++ CI

on:
  push:
    branches: [ knifer ]
  pull_request:
    branches: [ knifer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make -C 03_Implementation/
  
