name: C/C++ For windows 

on:
  push:
    branches: [ knifer ]
  pull_request:
    branches: [ knifer ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make -C 03_Implementation/windows
